[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.5", features = ["postgres", "runtime-tokio"] }
