[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.44.2", features = ["full"] }
